name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  MX_VERSION: '9.3.0.22930'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build image
      run: make version=${{env.MX_VERSION}} build
